services:
  php:
    build:
      context: docker/php
    volumes:
      - "./src:/var/www/html"
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx:/etc/nginx/conf.d"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./docker/mysql:/var/lib/mysql"
